name: wallet_wizard
description: wallet wizard app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  app_ui:
    path: packages/app_ui
  auto_route: ^7.8.3
  bloc: ^8.1.2
  build_runner: ^2.4.6
  dartz: ^0.10.1
  domain:
    path: packages/domain
  equatable: ^2.0.5
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  intl: ^0.18.0
  pinput: ^3.0.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  auto_route_generator: ^7.3.1
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
