// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAp4RETrAMrfMq6AY2RvB0pATF6dVCpyo',
    appId: '1:147572946095:web:ebcbe4c8c1655c6289d05a',
    messagingSenderId: '147572946095',
    projectId: 'wallet-wizzard',
    authDomain: 'wallet-wizzard.firebaseapp.com',
    storageBucket: 'wallet-wizzard.appspot.com',
    measurementId: 'G-MS7041J5MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb3MwbnYUWPfTrIta_hLDukbSHQTP5_to',
    appId: '1:147572946095:android:d11337e64acf07aa89d05a',
    messagingSenderId: '147572946095',
    projectId: 'wallet-wizzard',
    storageBucket: 'wallet-wizzard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH_GExQw8nzjv7_b7b_pqOf7RT9WEXpzs',
    appId: '1:147572946095:ios:4d7dda9f91e14e0c89d05a',
    messagingSenderId: '147572946095',
    projectId: 'wallet-wizzard',
    storageBucket: 'wallet-wizzard.appspot.com',
    iosBundleId: 'com.walletwizard.in.wallet-wizard',
  );
}
